# name: Go

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:

#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - name: Set up Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.17

#     - name: Build
#       run: |
#           # cd dmm
#           go install github.com/mitchellh/gox@v0.4.0
#           CGO_ENBLED=1 gox -os "linux" -arch "amd64"
#           ls

#     - name: Upload binaries to release
#       uses: svenstaro/upload-release-action@v2
#       with:
#         repo_token: ${{ secrets.GITHUB_TOKEN }}
#         file: dmm_*
#         tag: ${{ github.ref }}
#         overwrite: true
#         file_glob: true
